name: buckshot
description: Template-driven UI framework for building modern web applications.
version: 0.0.1
dependencies:
  unittest:
    sdk: unittest
  dartxml:
    git: git://github.com/prujohn/dart-xml.git