name: buckshot
description: >
  Buckshot is a multi-platform application framework. This core library provides
  the foundations for other target platforms to build from. Some of the core
  features provided include a template parser, data-binding, events,
  actions, style templates, and more.  Most developers will not import this core
  library directly, but will instead choose one of the platform  extension
  libraries (see https://github.com/prujohn/buckshot_html for the HTML5 platform).
version: 0.3.1
author: John Evans <prujohn@gmail.com>
homepage: http://www.buckshotui.org
dependencies:
  xml:
    git: git://github.com/prujohn/dart-xml.git
  dartnet_event_model:
    git: git://github.com/prujohn/DartNet-Event-Model.git
  html5lib: 'any'
  unittest:
    sdk: unittest
  logging:
    sdk: logging
  meta:
    sdk: meta
