name: buckshot
description: Template-driven UI framework for building modern web applications.
version: 0.0.1
author: John Evans <prujohn@gmail.com>
homepage: http://www.buckshotui.org
dependencies:
  unittest:
    sdk: unittest
  xml:
    git: git://github.com/prujohn/dart-xml.git
  dartnet_event_model:
    git: git://github.com/prujohn/DartNet-Event-Model.git
  dart_utils:
    git: git://github.com/prujohn/dart_utils.git