name:  switchy
description:  A sample application
dependencies: 
  buckshot: { git: git://github.com/prujohn/Buckshot.git }
  dartnet_event_model: { git: git://github.com/prujohn/DartNet-Event-Model.git }

